services:
    postgres:
        image: postgres:17.6-bookworm
        container_name: postgres_17_6
        restart: always
        environment:
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: pguser
            POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=zh_CN.UTF-8 --data-checksums"
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./conf:/etc/postgresql/conf.d
