services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: mysql_8_0_43
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - /opt/containerd/volume/mysql80/data:/var/lib/mysql
      - /opt/containerd/volume/mysql80/conf:/etc/mysql/conf.d
