services:
    mysql:
        image: mysql:8.0.43
        container_name: mysql_8_0_43
        restart: always
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./conf:/etc/mysql/conf.d
